### ISSUE TITLE
Not able to use the plugin for validating multiple jsons

### ISSUE THREAD

**Issue by songster-sa** [misl/openapi-validator-maven-plugin#14]
I have some 20+ open api v3 specs (one for each api version) that i want to validate. 
The plugin works fine for a single json file validation ( and i like the way the errors are spit out ), but its not feasible to validate multiple json files.

Is there a way to get around the below issues :

1. < inputSpec > is built to read only a single file. It neither accepts a directory or a <directory/*.json> format.
2. An output openapi.json is always created (under the default <target/generated-specification> path.

**Comment by misl** [comment]
Are these 20+ different APIs or do they together form a single API?
Normally every separate API has its own lifecycle. This justifies that is lives in its own repository with its own validation and its own version numbering. This plugin was build with this in mind.

If these 20+ however are together a single API (in my opinion) you should also supply a single spec file to your API consumers. This plugin is capable of merging multiple files together into a single spec file see [the complex example](https://github.com/misl/openapi-validator-maven-plugin/tree/master/examples/complex). Google is you friend regarding splitting up OpenAPI spec files. For example: https://davidgarcia.dev/how-to-split-open-api-spec-into-multiple-files

Maybe you can elaborate a bit more about your case and how your APIs are organized. For example are there any objects/models shared across your spec files?

**Comment by songster-sa** [comment]
Thanks for explaining the intent of the plugin. In my case, i have  20+ versions of an api.... and all versions are published. I have written the logic to validate the files, but was exploring if i can use this plugin.

**Comment by misl** [comment]
Do I understand correctly that it is 20+ versions of the same API? Or are these 20+ different APIs?

Whether or not this maven plugin could be useful for you depends on how your APIs were created. If you use an API first approach in which you start with defining your API using OpenAPI before the actual implementation, then I see added value in using this plugin. If however you use a code first approach in which OpenAPI/Swagger annotations are used in your implementation, then I see little added value.

If you follow the first approach (API first) I could help out if needed.

**Comment by misl** [comment]
No response, close issue
