### ISSUE TITLE
does it really validate the schema?

### ISSUE THREAD

**Issue by fabiohecht** [misl/openapi-validator-maven-plugin#17]
Hi, I'm looking for a syntax checker (validator) for openapi 3. While testing this project, I tried 2 invalid specs: One has a "type" which is invalid, and the other has a required field which is not defined. Both were validated fine. Is this a bug or did I miss anything?

It could also be useful to disable the conversion part for those (like me) that are looking for a validator and end up here because of the project name.

Cheers,

Fabio

**Comment by misl** [comment]
Hi Fabio,

Thanks for checking out my project. 

Internally this maven plugin uses the swagger parser

```
        <dependency>
            <groupId>io.swagger.parser.v3</groupId>
            <artifactId>swagger-parser</artifactId>
            <version>2.0.19</version>
        </dependency>
```

So whatever that parser accepts I consider validated. 

Regarding conversion, it could be extended to disable merging together several partial specifications. On the other had you can also ignore the merged output. 

I accept pull requests ;-)

Regards,

Minto

**Comment by fabiohecht** [comment]
Alright, thanks for the clarification!
