### ISSUE TITLE
Same operationId not reported as issue

### ISSUE THREAD

**Issue by vlavasa** [misl/openapi-validator-maven-plugin#22]
Hi,
I would like report this bug:
I have API definition split into multiple files linked together by $ref.
I use this plugin for merging API to one-file version, because tools as WSO, Postman etc. still not support splitted definition.

If in two diferent files there are two diferent paths with the same operationId, plugin's validation not report this as issue. But final merged file is not valid, because unique operationId is required.

Best regards
Vladimir

**Comment by misl** [comment]
This is an error in the underlying swagger parser being used. The plugin is just a very thing layer. Please report the error over there.
